common_packages:
  - aptitude # apt terminal gui
  - arandr # Visual frontend for xrandr
  - autorandr # Automatically select a display configuration based on connected devices
  - bat # cat alternative
  - brightnessctl # Command line brightness control
  - btop # htop alternative
  - clamav # closest thing to an antivirus on linux
  - clamav-daemon # daemon for ^
  - copyq # Clipboard manager
  - curl # Client URL
  - direnv # Auto load env (if .envrc or .env exist)
  - dog # dig alternative
  - exa # ls alternative
  - feh # Image viewer and desktop wallpaper
  - fd-find # find alternative
  - fzf # Terminal Fuzzy finder
  - gimp # like photoshop, but for nix
  - git # Version control
  - gitk # git tree visualizer
  - htop # System monitor
  - jq # Command-line JSON processor
  - make # make utility automation
  - mc # Terminal file manager
  - mosh # Mobile shell (like ssh)
  - ncdu # Disk usage analyzer
  - neofetch # Terminal system info
  - pavucontrol # Pulseaudio volume control
  - peco # Terminal fuzzy finder
  - playerctl # Terminal media controler
  - powertop # Energy optimizer
  - ranger # Terminal directory manager (vimlike)
  - ripgrep # Regex dir finder
  - rclone # rsync for cloud storage
  - scrcpy # mirror android screen
  - solaar # logitech device manager
  - shellcheck # shell script static analysis tool
  - syncthing # Sync folders between computers
  - tldr # like man but just examples
  - tlp # Energy optimizer
  - tree # Directory tree
  - vlc # Media player
  - xdg-utils # Desktop integration utilities
  - xdotool # x do tool
  - wget # Web get
  - zoxide # Smart cd command
