common_packages:
  - curl # Client URL
  - fzf # Terminal Fuzzy finder
  - gimp # like photoshop, but for nix
  - git # Version control
  - htop # System monitor
  - mc # Terminal file manager
  - ncdu # Disk usage analyzer
  - neofetch # Terminal system info
  - peco # Terminal fuzzy finder
  - tldr # like man but just examples
  - tree # Directory tree
  - ranger # Terminal directory manager (vimlike)
  - rclone # rsync for cloud storage
  - scrcpy # mirror android screen
  - syncthing # Sync folders between computers
  - wget # Web get

debian_packages:
  - aptitude # apt terminal gui
  - tlp # Energy optimizer
  - powertop # Energy optimizer
  - solaar # logitech device manager
