common_packages:
  - arandr # Visual frontend for xrandr
  - autorandr # Automatically select a display configuration based on connected devices
  - bat # cat alternative
  - brightnessctl # Command line brightness control
  - btop # htop alternative
  - clamav # closest thing to an antivirus on linux
  - copyq # Clipboard manager
  - curl # Client URL
  - direnv # Auto load env (if .envrc or .env exist)
  - feh # Image viewer and desktop wallpaper
  - fd-find # find alternative
  - fzf # Terminal Fuzzy finder
  - gimp # like photoshop, but for nix
  - git # Version control
  - gitk # git tree visualizer
  - htop # System monitor
  - jq # Command-line JSON processor
  - keychain # Keychain manager
  - make # make utility automation
  - mc # Terminal file manager
  - mosh # Mobile shell (like ssh)
  - ncat # Netcat alternative
  - ncdu # Disk usage analyzer
  - pavucontrol # Pulseaudio volume control
  - playerctl # Terminal media controler
  - powertop # Energy optimizer
  - pulseaudio-utils # tools for audio control
  - ranger # Terminal directory manager (vimlike)
  - ripgrep # Regex dir finder
  - rclone # rsync for cloud storage
  - solaar # logitech device manager
  - shellcheck # shell script static analysis tool
  - syncthing # Sync folders between computers
  - tldr # like man but just examples
  - trash-cli # Command line trash utility
  - tree # Directory tree
  - vim # VIM
  - vlc # Media player
  - xdg-utils # Desktop integration utilities
  - xdotool # x do tool
  - wev # imput analyzer
  - wget # Web get
  - yq # like jq, but for yaml
  - zoxide # Smart cd command
