
- name: Run the equivalent of "apt-get update" as a separate step
  become: yes
  apt:
    update_cache: yes

- name: Upgrade existing packages
  become: yes
  apt:
    upgrade: safe

- name: Installs common packages apt
  become: yes
  loop: "{{ common_packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Installs debian packages apt
  become: yes
  loop: "{{ debian_packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Cleans packages | apt
  become: yes
  apt:
    autoremove: yes
