- name: Add mem_sleep_default=deep var to the GRUB_CMDLINE_LINUX_DEFAULT variables
  lineinfile: 
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=(?!.* mem_sleep_default)\"[^\"]+)(\".*)'
    line: '\1 mem_sleep_default=deep\2'
    backrefs: yes
    state: present

- name: update-grub
  shell: update-grub2